Pb-4844: Made changes in kdmp for it to enable debug level log messages
portworx/kdmp pull request #324
Opened 2023-11-27 11:06 UTC by kgarg-px

**What this PR does / why we need it**:
This PR introduces changes to include the debug level of logs for all kopia related operations. Needed, so it can be easier to debug any messages in the future when required.
**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:
Attaching screenshots for reference 
![Screenshot 2023-11-27 at 4 05 47 PM](https://github.com/portworx/kdmp/assets/148333439/54c7427a-b1b9-4545-b50b-547e617bf5fe)
![Screenshot 2023-11-27 at 4 12 44 PM](https://github.com/portworx/kdmp/assets/148333439/e69de812-276d-4210-8ed9-52516d7568ab)
![Screenshot 2023-11-27 at 4 15 43 PM](https://github.com/portworx/kdmp/assets/148333439/d4625e8c-94a1-46a6-821a-650c8426fe3c)
![Screenshot 2023-11-27 at 10 50 26 AM](https://github.com/portworx/kdmp/assets/148333439/7d1d7767-adba-4bc5-8d0a-43a66bb99554)

2023-11-28 06:09 UTC, vsundarraj-px requested changes

2023-11-28 06:09 UTC, vsundarraj-px commented on pkg/executor/kopia/kopiabackup.go
> +	if err := initExecutor.Run(logLevel); err != nil {
I think too much changes have happened because the basic signature has been changed. The best way is to use use internal options than as function argument. You can follow how other options have been used without changing Run() signature and follow the same. 

This applies to all places where existing function signature is changed to add loglevel.

nit:  in general log-levels has multiple levels. Info/error/trace/debug. I see log-level means debug only. .. You should use specific name if there are no multiple values it can take. if debug is what you mean specifically, you should change it to enable-debug-logging or log-level-debug

2023-11-28 17:05 UTC, prashanthpx commented on pkg/executor/kopia/kopiabackup.go
> +	if err := initExecutor.Run(logLevel); err != nil {
+1 for the above

2023-11-29 05:00 UTC, kgarg-px commented on pkg/drivers/kopiabackup/kopiabackup.go
> +func checkDataExportAnnotation(jobOption drivers.JobOpts) bool {
made changes accordingly

2023-11-29 05:00 UTC, kgarg-px commented on pkg/drivers/kopiarestore/kopiarestore.go
> +	if checkDataExportAnnotation(jobOption) {
Made changes

2023-11-29 05:01 UTC, kgarg-px commented on pkg/drivers/kopiarestore/kopiarestore.go
> +func checkDataExportAnnotation(jobOption drivers.JobOpts) bool {
Moved the function to pkg/drivers/utils/utils.go

2023-11-29 05:01 UTC, kgarg-px commented on pkg/executor/kopia/kopiabackup.go
> +	if err := initExecutor.Run(logLevel); err != nil {
Made the suggested changes and tested as well with new changes

2023-11-29 10:25 UTC, vsundarraj-px requested changes

2023-12-01 13:59 UTC, siva-portworx commented
@kgarg-px Can you add the new debug message that we are getting, when you enabled debug option for kopia? In the screenshot i do not see any new messsage from kopia tool code. All the messages that i see are from kopia-executor code.

2023-12-04 05:40 UTC, kgarg-px commented
> @kgarg-px Can you add the new debug message that we are getting, when you enabled debug option for kopia? In the screenshot i do not see any new messsage from kopia tool code. All the messages that i see are from kopia-executor code.

@siva-portworx 
The only new messages from kopia tool are visible only in the case of `backup` and `maintenance` at times.

2023-12-06 10:11 UTC, vsundarraj-px requested changes

2023-12-06 10:11 UTC, vsundarraj-px commented on pkg/executor/kopia/kopiabackup.go
> +func isKopiaDebugModeEnabled(kopiaCommand *kopia.Command, logLevelDebug string) *kopia.Command {
You should remove this function and add this check in addLogLevelDebugtoCommand() 
isKopiaDebugModeEnabled() sounds like check function and should not set any thing in this. 
But as suggested this function can be removed.

2023-12-06 10:11 UTC, vsundarraj-px commented on pkg/executor/kopia/kopiadelete.go
> +	deleteCmd = isKopiaDebugModeEnabled(deleteCmd, logLevelDebug)
As suggested above replace this with addLogLevelDebugToCommand() after moving the check code inside this function

2023-12-06 10:11 UTC, vsundarraj-px commented on pkg/executor/kopia/maintenance.go
> +	maintenanceRunCmd = isKopiaDebugModeEnabled(maintenanceRunCmd, logLevelDebug)
Same here..and every place where isKopiaDebugEnabled() is called.

2023-12-06 10:11 UTC, vsundarraj-px commented on pkg/executor/kopia/restore.go
> +
remove extra space

2023-12-06 10:11 UTC, vsundarraj-px commented on pkg/kopia/command.go
> +
Remove all extra lines

2023-12-08 02:31 UTC, vsundarraj-px approved these changes
LGTM

2023-12-11 05:11 UTC, prashanthpx commented on pkg/executor/kopia/kopiabackup.go
> +	repoCreateCmd = addLogLevelDebugToCommand(repoCreateCmd, logLevelDebug)
Ideally we should move this adding to args in command.go file as this is commong to all flow path. We can set to enable debug mode in `type Command` struct and use that to fill details in all places.

2023-12-11 05:55 UTC, kgarg-px commented on pkg/drivers/kopiabackup/kopiabackup.go
> +				Resources: []string{"volumebackups", "dataexports"},
@prashanthpx The reason why we are using DE CR here is because, we are setting certain annotations in the DE CR while reading the key-value pair from the `kdmp-config` CM, if a particular key-value pair is present, then we set the annotation in the DE CR, and in kdmp, we are reading the DE CR and seeing if the particular annotation is present, upon which we enable the debug mode in kopia

2023-12-12 04:27 UTC, prashanthpx commented on pkg/executor/kopia/kopiabackup.go
> +	repoCreateCmd = addLogLevelDebugToCommand(repoCreateCmd, logLevelDebug)
Fine for now but flow is for few things which are very specific to command we add it and common things goes to Command struct.

2023-12-12 04:45 UTC, prashanthpx commented on pkg/drivers/kopiabackup/kopiabackup.go
> +				Resources: []string{"volumebackups", "dataexports"},
Looking at the stork PR, my understanding on the flow is 
1. You read the CM in stork
2. Pass the Debug mode in the DE CR

Indeed we need not do this way as reconciler code in kdmp does read `kdmp-config` value (for eg check `KopiaResourceRequirements`) where we can set kdmp job resoruces on the fly.
We should be following the same with which, we won't need any stork change except vendoring the code to stork

2023-12-14 17:03 UTC, prashanthpx approved these changes
LGTM. Before merging can you pls remove the vendor code of strok as it is not needed.

2023-12-18 14:11 UTC, merged