PB-4572:Added logging of pod describe,events and Jobpod log in job failure scenarios
portworx/kdmp pull request #341
Opened 2024-02-05 14:02 UTC by aks-px

**What this PR does / why we need it**:
1.Added utility function to display the job pod log,events and description.
Added the call to the jobStatus function where we check the status of job to print logs in case of failure.

2.Code cleanup: Removed unnecessary *err!=nil* blocks and removed appendPodLogtoStork function 
3.Fix label for NFSCSIrestore job which was pointing to NFSRestore before
**Which issue(s) this PR fixes** (optional)
Closes #PB-4572

**Special notes for your reviewer**:
Screenshots of 
1.kopiabackup driver mountfailed and job failed:
![Screenshot 2024-01-29 at 11 45 52 AM](https://github.com/portworx/kdmp/assets/123449175/710ec692-bdc3-492b-a2a1-e27230daf375)
![Screenshot 2024-01-30 at 11 42 10 AM](https://github.com/portworx/kdmp/assets/123449175/02247231-9c30-4de2-b983-775426232ce7)
2.nfsbackup mount and job failed:
![Screenshot 2024-02-03 at 11 05 17 PM](https://github.com/portworx/kdmp/assets/123449175/2321c655-0566-4466-9a3c-286de5df69dc)
<img width="1728" alt="Screenshot 2024-02-04 at 12 06 27 AM" src="https://github.com/portworx/kdmp/assets/123449175/380a2873-67e0-4696-ac3a-ef79f1d44fb8">
<img width="1728" alt="Screenshot 2024-02-04 at 12 06 40 AM" src="https://github.com/portworx/kdmp/assets/123449175/d952bccd-e131-4e3f-9328-ab8732ffdfa7">
<img width="1728" alt="Screenshot 2024-02-04 at 12 06 48 AM" src="https://github.com/portworx/kdmp/assets/123449175/6eb2e013-1c12-45cd-b6d4-919f75690a87">
kopiarestore mount fail:
![Screenshot 2024-01-29 at 6 21 28 PM](https://github.com/portworx/kdmp/assets/123449175/0a1ff9c1-2a7a-411f-a522-b4e6c827843a)

nfsrestore mount and job fail:
![Screenshot 2024-01-29 at 5 56 20 PM](https://github.com/portworx/kdmp/assets/123449175/3fa6f704-88c9-4fd0-82d2-4bed20a1f9f3)
<img width="1728" alt="Screenshot 2024-02-04 at 9 58 06 PM" src="https://github.com/portworx/kdmp/assets/123449175/825e70ea-c00e-411e-b33b-6ead6fd44a6e">
<img width="1728" alt="Screenshot 2024-02-04 at 9 58 19 PM" src="https://github.com/portworx/kdmp/assets/123449175/e40c437e-fde4-451f-8ade-32bd31f0d76f">
<img width="1728" alt="Screenshot 2024-02-04 at 9 58 38 PM" src="https://github.com/portworx/kdmp/assets/123449175/1d881023-2369-43e0-930b-b62d26165584">
NFSCSIrestore:
![Screenshot 2024-02-05 at 2 14 34 PM](https://github.com/portworx/kdmp/assets/123449175/2954139b-e80d-4c3b-9e6b-2c8332ca9df8)
![Screenshot 2024-02-05 at 3 31 12 PM](https://github.com/portworx/kdmp/assets/123449175/fbf8a251-8f0b-4989-a8fd-6b8c990b3283)

Delete and maintenace related screenshot will be added in the PR for px-backup

2024-02-06 10:34 UTC, vikasit12 commented on pkg/drivers/utils/utils.go
> +	for _, pod := range pods.Items {
please put it under else condition

2024-02-06 10:34 UTC, vikasit12 commented on pkg/drivers/utils/utils.go
> +			logrus.Infof("error fetching description of job-pod [%s] in namespace [%s].err: %v", pod.Name, pod.Namespace, err)
NIT :: no space between ns and error

2024-02-06 10:34 UTC, vikasit12 commented on pkg/drivers/utils/utils.go
> +		logrus.Infof("failed to fetch pod of job [%v] in namespace [%v].err: %v", jobName, namespace, err)
NIT :: no space between ns and error

2024-02-06 12:01 UTC, aks-px commented on pkg/drivers/utils/utils.go
> +		logrus.Infof("failed to fetch pod of job [%v] in namespace [%v].err: %v", jobName, namespace, err)
Addressed all the changes mentioned.Please review again.

2024-02-06 13:46 UTC, vsundarraj-px requested changes
Should you need to change failed and error message to Errorf instead of Infof

2024-02-06 13:46 UTC, vsundarraj-px commented on pkg/controllers/resourceexport/reconcile.go
> +						logrus.Infof("job-pod name and namespace extraction failed: %v", err)
Any reason why failed message is logged as Infof?

2024-02-06 13:46 UTC, vsundarraj-px commented on pkg/drivers/utils/utils.go
> +		logrus.Infof("failed to get job [%v] in namespace [%v]. Error is: %v", jobName, namespace, err)
Same here, failed is logged as Infof

2024-02-06 13:46 UTC, vsundarraj-px commented on pkg/drivers/utils/utils.go
> +				logrus.Infof("error fetching description of job-pod [%s] in namespace [%s]. Error is: %v", pod.Name, pod.Namespace, err)
Here too

2024-02-06 14:20 UTC, px-kesavan requested changes

2024-02-06 14:20 UTC, px-kesavan commented on pkg/drivers/utils/utils.go
> +	if err != nil && !apierrors.IsNotFound(err) {
Return when job is not found , checking for the existence of the job pod when job is not available is not relavent

2024-02-06 14:20 UTC, px-kesavan commented on pkg/controllers/resourceexport/reconcile.go
> +					}
Is it job name or job pod name ?

2024-02-06 14:20 UTC, px-kesavan commented on pkg/drivers/kopiabackup/kopiabackup.go
> +		utils.DisplayJobpodLogandEvents(job.Name, job.Namespace)
Why we are displaying the logs and events if in case of volume backup failure ?. was it intended for jobpending scenario ?

2024-02-06 14:20 UTC, px-kesavan commented on pkg/drivers/kopiarestore/kopiarestore.go
> +		utils.DisplayJobpodLogandEvents(job.Name, job.Namespace)
Does it make sense to add for job pending as well ?.. job pod events gives the reason for pending

2024-02-06 14:20 UTC, px-kesavan commented on pkg/drivers/nfsbackup/nfsbackup.go
> +		utils.DisplayJobpodLogandEvents(job.Name, job.Namespace)
Same here, can we consider adding it for pending case as well ?

2024-02-06 17:42 UTC, aks-px commented on pkg/controllers/resourceexport/reconcile.go
> +				if resourceExport.Status.TransferID != "" {
Okay

2024-02-06 17:59 UTC, aks-px commented on pkg/controllers/resourceexport/reconcile.go
> +						logrus.Infof("job-pod name and namespace extraction failed: %v", err)
My bad ,will change all occurance to Errorf.

2024-02-06 17:59 UTC, aks-px commented on pkg/controllers/resourceexport/reconcile.go
> +					}
It's Jobname.will do the required changes

2024-02-07 07:04 UTC, aks-px commented on pkg/drivers/nfsbackup/nfsbackup.go
> +		utils.DisplayJobpodLogandEvents(job.Name, job.Namespace)
As discussed and after discussion with @siva-portworx ,considering this scenario for logging in future as every job when started will also be in pending and displaying the logs then is a concern that needs to be handled.

2024-02-08 02:49 UTC, vsundarraj-px approved these changes
LGTM

2024-02-08 06:50 UTC, px-kesavan approved these changes
LGTM

2024-02-08 10:39 UTC, merged