Adding support for anyuid annotation in case of OCP
portworx/kdmp pull request #401
Opened 2024-11-15 06:29 UTC by dbinnal-px

**What this PR does / why we need it**:
This PR is to fix the IBM customer issue which is described in this ticket https://purestorage.atlassian.net/browse/PB-8586 

Where we are trying to add anyuid annotations to any required provisioners on OCP cluster

**Which issue(s) this PR fixes** (optional)
Closes #
https://purestorage.atlassian.net/browse/PB-8630

**Special notes for your reviewer**:

Took kdmp backup of the DB2 application running on IBM ROKS cluster with storage provisioner  ibm-vpc-file 
Backup create successfully along with which the anyuid annotation was added to kdmp jobs running on the application cluster
![Screenshot 2024-11-14 at 3 39 23 PM](https://github.com/user-attachments/assets/8e97bfd6-90cd-4705-abde-a33cb42eb475)
![Screenshot 2024-11-15 at 11 57 54 AM](https://github.com/user-attachments/assets/1b18a292-fdc2-4440-891b-b9fa5c4e38f9)

Testing on other scenarios is still in Progress

2024-11-18 07:45 UTC, lalat-das requested changes

2024-11-18 07:45 UTC, lalat-das commented on pkg/drivers/rsync/rsync.go
> +	if err := utils.SetupServiceAccount(jobName, namespace, srcVol, roleFor(utils.RsyncOpenshiftSCC())); err != nil {
Why are we changing rsync ?? it is not necessary I guess.

2024-11-18 07:45 UTC, lalat-das commented on pkg/drivers/utils/utils.go
> +		logrus.Infof("PROVISIONERS_TO_USE_ANYUID is set to use, running the job %v with anyuid SCC", job.Name)
This line is misleading here. If the provisioner name passed is not found in the PVC yaml, I mean the if condition mentioned below fails then new are not using ANYUID..

2024-11-18 07:45 UTC, lalat-das commented on pkg/drivers/utils/utils.go
> +	if err := json.Unmarshal([]byte(jsonData), &arrayData); err != nil {
Will this unmarshall work in all scenarios , I mean does this depend on the string supplied as part of configmap to be in certain pattern. Then highlight that in comment. It helps in debugging. Remember to add it inn Doc if at all there is any

2024-11-19 05:10 UTC, lalat-das approved these changes
lgtm

2024-11-19 06:42 UTC, vsundarraj-px commented on pkg/drivers/utils/common.go
> +	kdmpConfigMap, err := coreops.Instance().GetConfigMap(KdmpConfigmapName, KdmpConfigmapNamespace)
is this same asextractArrayFromKdmpConfigMap? Can you resuse the API instead of reading it outside?

2024-11-19 06:45 UTC, vsundarraj-px commented on pkg/drivers/utils/utils.go
> +func extractArrayFromKdmpConfigMap(key string) ([]string, error) {
Please make it generic function. We already have utils to read from configMap, but that only returns string not array of string. I understand the requirement of this function but its better you make it generic 
GetArrayConfigValue(configMapName, configMapNs string) ([]string, error)

2024-11-19 06:46 UTC, vsundarraj-px commented on pkg/drivers/utils/utils.go
> +	kdmpData, err := core.Instance().GetConfigMap(KdmpConfig, defaultPXNamespace)
You should use existing getConfigValue() and parse the result and split

2024-11-19 06:47 UTC, vsundarraj-px commented on pkg/drivers/utils/utils.go
> +// this function extracts an array from a kdmp-config
General approach for function comment. 
// <function name> describe what the function does. 

more precise which will help the reviewer is to add 
// input parameters
// returns
// error conditions.

2024-11-19 06:48 UTC, vsundarraj-px reviewed
Provided some comments

2024-11-19 09:27 UTC, vsundarraj-px approved these changes
nit: please see if you can follow the existing logrus.Errorf() format across where setupRoleBindingForSCC() is handled.

2024-11-20 03:11 UTC, merged